### ISSUE TITLE
AttributeError: 'SmallData' object has no attribute 'summary'

### ISSUE THREAD

**Issue by muammar** [slac-lcls/lcls2#11]
When I run the [Small H5 example](https://confluence.slac.stanford.edu/display/PSDMInternal/Small+H5), the script works up to the point where it tries to print a summary with the following error: 

```
Traceback (most recent call last):
  File "example.py", line 25, in <module>
    if smd.summary:
AttributeError: 'SmallData' object has no attribute 'summary'
Traceback (most recent call last):
  File "example.py", line 25, in <module>
    if smd.summary:
AttributeError: 'SmallData' object has no attribute 'summary'
Traceback (most recent call last):
  File "example.py", line 25, in <module>
    if smd.summary:
AttributeError: 'SmallData' object has no attribute 'summary'
Traceback (most recent call last):
  File "example.py", line 25, in <module>
    if smd.summary:
AttributeError: 'SmallData' object has no attribute 'summary'
```
`.summary` seems to be a boolean that probably was not instantiated in some of the previous lines of code?

**Comment by chrisvam** [comment]
Closing this issue since it's old:  I missed it because I didn't have GitHub notifications enabled for this repo, which I think I have now fixed.  And we have talked to Muammar many times since then, so I believe it's working for him.
